### ISSUE TITLE
When I Put Python2 crack.py it comes

### ISSUE THREAD

**Issue by Strikecodes** [htr-tech/pakcrack#6]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/data/data/com.termux/files/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "init_enc.py", line 26, in <module>
  File "<string>", line 1, in <module>
  File "<tahm1d>", line 5, in <module>
  File "<string>", line 4, in <module>
  File "<tahm1d>", line 25, in <module>
  File "<string>", line 1, in <module>
  File "<tahm1d>", line 5, in <module>                                   File "<string>", line 4, in <module>
  File "<tahm1d>", line 19, in <module>
  File "<string>", line 1, in <module>                                   File "<tahm1d>", line 37, in <module>
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/crkpk/__init__.py", line 11, in <module>
    x1e\xac\xa6\xd78\xbaE\xf7_U\xfd\xc6\x01\xd8}#\xa1\x12\x0f\x9f\xc8P\x1e\xb3\xd0\xba\xccWR\x02\xd0y\x80\xf7)\x9a\x95\x7fyg\x014\xc3\x87\xca\xb2%\xe4(a\xf4\xd7)\x03/\n\xa0!\x9f\x80r\x81\xaeXN\xca\xf0l\xd3\xb6im\xdf\xedI=\xd4\xee\xe8#P&\x1b&\xb5\x18\xb5V\x1b\xad\xe0\xe9s\x8b\xb5m\x06\x9f\xd9\xb6.d\x15\xc8\xde\xb9\x1f\xc0\x92\x8b\xe6\x10\x05\xad\xf2`\xe5\x1e\xc6$\xa3\xa6Q\x88\x01\x1f\xe6\xb8\xb7\x18O\xcffR\x0c\xbbcE\xad\xbc\xf5\x0b\xb9\x9a\x9f\x05\x04\xc7L\x93\xa1\xf6\xe7\xd7k\x06\xca\xb0!\x0c\x86|0\xbbm\xff\xd5\xb7\xeaCo\xd8\xdc\xc4z\xc5\x18\xec\xc4\xe6\x02\x95\x84 Q\x8a\xbbE\xbe2\xb9\xbe\xe8%g\xddP\xb9\x92\xf7O\xbe\xa8\xbcS\xc0\xa5\xf7\xee\xd2\xec\x8c\xe3\x0c \x92n\xb2\x91\xb3\xa3j\xa8\xf0YD\xd5\xb0]\xcc\xa5\xb8K\xee\xeb\xb3\x9d\xa3e\xd8\rwUi\x02\x9d\xbc\x7fjONi\xb8\xb2\xd2\x80\xf5m\xdd\xea\xecvu\x13\x89\x04\x13\xdb\x02\x9a\x03\xe8\xa7m\xa8\xb3\x9e+\xa7\x18TC\xddSV_\xa2%*|\xa5\xe6G<\xcb\xe9\xd3J\xe8\xac\x121oYN\x98\xbffd\xd2w\xeb\xef\xc5Id\x9fg\xba\xb1f\xa7\xb0O\x7f\xef\xd9\n\xf6\xeeP\xa0nw\'\x0e\xebse\xf1b-\x1a\x03e Z!>\x89Y6\x82/\x8a\x1a\x0b\xe8\xc9\xd7\xe9\xe6\xcd\xa9\xff\x01\x846A\x88')                              File "<string>", line 2, in <module>                                   File "<string>", line 2, in <module>                                   File "<string>", line 1, in <module>                                   File "<string>", line 10, in <module>                                  File "<tahm1d>", line 35, in <module>                                  File "<string>", line 1, in <module>                                   File "<tahm1d>", line 17, in <module>                                  File "", line 5, in <module>                                                                                                                  File "<string>", line 4, in <module>                                   File "", line 109, in <module>                                       
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pastebin.com', port=443): Max retries exceeded with url: /raw/4sGakiW6 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xf0ec4ad0>: Failed to establish a new connection: [Errno 7] No address associated with hostname',))

**Comment by htr-tech** [comment]
@Strikecodes you need an active internet connection :/

**Comment by Strikecodes** [comment]
I do have.

**Comment by Nitesh-mint** [comment]
unable to install request!
unable to install mechanize!

**Comment by htr-tech** [comment]
> unable to install request!
> unable to install mechanize!

pip2 install requests mechanize crkpk

& try again
